"""Install / uninstall native messaging host manifests for browsers."""

from __future__ import annotations

import json
import platform
import stat
from dataclasses import dataclass
from pathlib import Path
from typing import Any

HOST_NAME = "com.yoink.host"
HOST_DESCRIPTION = "yoink download manager native host"

# Wrapper script that invokes the daemon from the active venv / install.
HOST_WRAPPER_TEMPLATE = """#!/bin/sh
# Auto-generated by `yoink install-browser-host`. Do not edit.
exec {python} -m yoink.browser.native_host
"""


@dataclass(frozen=True)
class BrowserConfig:
    """Where to install the manifest for a given browser on this OS."""

    name: str
    user_manifest_dir: Path
    system_manifest_dir: Path | None = None


def configs_for_platform() -> list[BrowserConfig]:
    """Return install locations for all supported browsers on this OS."""
    system = platform.system()
    home = Path.home()
    configs: list[BrowserConfig] = []

    if system == "Darwin":
        configs = [
            BrowserConfig(
                name="Chrome",
                user_manifest_dir=home
                / "Library/Application Support/Google/Chrome/NativeMessagingHosts",
            ),
            BrowserConfig(
                name="Brave",
                user_manifest_dir=home
                / "Library/Application Support/BraveSoftware/Brave-Browser/NativeMessagingHosts",
            ),
            BrowserConfig(
                name="Edge",
                user_manifest_dir=home
                / "Library/Application Support/Microsoft Edge/NativeMessagingHosts",
            ),
            BrowserConfig(
                name="Firefox",
                user_manifest_dir=home / "Library/Application Support/Mozilla/NativeMessagingHosts",
            ),
        ]
    elif system == "Linux":
        xdg = Path.home() / ".config"
        configs = [
            BrowserConfig(
                name="Chrome",
                user_manifest_dir=xdg / "google-chrome/NativeMessagingHosts",
            ),
            BrowserConfig(
                name="Brave",
                user_manifest_dir=xdg / "BraveSoftware/Brave-Browser/NativeMessagingHosts",
            ),
            BrowserConfig(
                name="Chromium",
                user_manifest_dir=xdg / "chromium/NativeMessagingHosts",
            ),
            BrowserConfig(
                name="Firefox",
                user_manifest_dir=xdg / ".mozilla/NativeMessagingHosts",
            ),
        ]
    elif system == "Windows":
        # Windows uses registry, not manifest files. Caller handles separately.
        configs = [
            BrowserConfig(
                name="Chrome",
                user_manifest_dir=Path.home() / "AppData/Local/yoink",
            ),
        ]

    return configs


def install_host(
    *,
    python_bin: Path,
    browser: str | None = None,
    extension_ids: list[str],
    wrapper_dir: Path | None = None,
) -> list[Path]:
    """Install the native host wrapper + manifest(s). Returns paths written."""
    # Write wrapper script.
    wrapper_dir = wrapper_dir or Path.home() / ".yoink"
    wrapper_dir.mkdir(parents=True, exist_ok=True)
    wrapper_path = wrapper_dir / "yoink-host.sh"
    wrapper_path.write_text(
        HOST_WRAPPER_TEMPLATE.format(python=str(python_bin)),
        encoding="utf-8",
    )
    wrapper_path.chmod(wrapper_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    # Build manifest.
    manifest: dict[str, Any] = {
        "name": HOST_NAME,
        "description": HOST_DESCRIPTION,
        "path": str(wrapper_path),
        "type": "stdio",
    }
    # Firefox uses `allowed_extensions` (extension IDs without prefix).
    # Chromium uses `allowed_origins` (with chrome-extension:// prefix).
    if extension_ids:
        manifest["allowed_origins"] = [f"chrome-extension://{eid}/" for eid in extension_ids]
        manifest["allowed_extensions"] = list(extension_ids)

    # Decide which browsers to install for.
    all_configs = configs_for_platform()
    if browser:
        target = browser.lower()
        all_configs = [c for c in all_configs if c.name.lower() == target]

    written: list[Path] = [wrapper_path]
    for cfg in all_configs:
        cfg.user_manifest_dir.mkdir(parents=True, exist_ok=True)
        manifest_path = cfg.user_manifest_dir / f"{HOST_NAME}.json"
        manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
        written.append(manifest_path)

    return written


def uninstall_host(*, browser: str | None = None) -> list[Path]:
    """Remove manifest files. Returns paths removed."""
    all_configs = configs_for_platform()
    if browser:
        target = browser.lower()
        all_configs = [c for c in all_configs if c.name.lower() == target]

    removed: list[Path] = []
    for cfg in all_configs:
        manifest_path = cfg.user_manifest_dir / f"{HOST_NAME}.json"
        if manifest_path.exists():
            manifest_path.unlink()
            removed.append(manifest_path)
    return removed
